FROM httpd:2.4

RUN apt-get update

# build-essential: gcc, g++
# cppcheck used for static code analysis
# libcurl4-gnutls-dev used for integration testing

RUN apt-get install -y build-essential cppcheck libcurl4-gnutls-dev vim

